// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Daggerer struct { // daggerer (../../../:0:0)
	query *querybuilder.Selection

	build   *string
	deploy  *Void
	id      *ID
	release *Void
}

func (r *Daggerer) WithGraphQLQuery(q *querybuilder.Selection) *Daggerer {
	return &Daggerer{
		query: q,
	}
}

// DaggererBuildOpts contains options for Daggerer.Build
type DaggererBuildOpts struct {

	// Default: "latest"
	Tag string
	// Registry password mount path inside the registry client.
	//
	// Default: "/run/secrets/registry_password"
	RegistryPasswordMountPath string
	// Public .env file, parsed by Dagger. Never supply credentials here.
	BuildEnvFile *File
	// Public values constructed with EnvFile.WithVariable; override file values.
	BuildValues *EnvFile
	// Private .env mounted intact as the BuildKit secret build_env.
	BuildSecretEnv *Secret
	// BuildKit secret IDs, paired by position with buildSecrets.
	BuildSecretIds []string
	// Secret values, paired by position with buildSecretIDs.
	BuildSecrets []*Secret
	// Dockerfile path relative to the build context.
	//
	// Default: "Dockerfile"
	Dockerfile string
}

// Build and publish an image.
func (r *Daggerer) Build(ctx context.Context, source *Directory, registry string, appName string, registryUsername string, registryPassword *Secret, opts ...DaggererBuildOpts) (string, error) {
	assertNotNil("source", source)
	assertNotNil("registryPassword", registryPassword)
	if r.build != nil {
		return *r.build, nil
	}
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `tag` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tag) {
			q = q.Arg("tag", opts[i].Tag)
		}
		// `registryPasswordMountPath` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordMountPath) {
			q = q.Arg("registryPasswordMountPath", opts[i].RegistryPasswordMountPath)
		}
		// `buildEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildEnvFile) {
			q = q.Arg("buildEnvFile", opts[i].BuildEnvFile)
		}
		// `buildValues` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildValues) {
			q = q.Arg("buildValues", opts[i].BuildValues)
		}
		// `buildSecretEnv` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecretEnv) {
			q = q.Arg("buildSecretEnv", opts[i].BuildSecretEnv)
		}
		// `buildSecretIds` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecretIds) {
			q = q.Arg("buildSecretIds", opts[i].BuildSecretIds)
		}
		// `buildSecrets` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecrets) {
			q = q.Arg("buildSecrets", opts[i].BuildSecrets)
		}
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("registry", registry)
	q = q.Arg("appName", appName)
	q = q.Arg("registryUsername", registryUsername)
	q = q.Arg("registryPassword", registryPassword)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// DaggererBuildOnlyOpts contains options for Daggerer.BuildOnly
type DaggererBuildOnlyOpts struct {
	// Public .env file, parsed by Dagger. Never supply credentials here.
	BuildEnvFile *File
	// Public values constructed with EnvFile.WithVariable; override file values.
	BuildValues *EnvFile
	// Private .env mounted intact as the BuildKit secret build_env.
	BuildSecretEnv *Secret
	// BuildKit secret IDs, paired by position with buildSecrets.
	BuildSecretIds []string
	// Secret values, paired by position with buildSecretIDs.
	BuildSecrets []*Secret
	// Dockerfile path relative to the build context.
	//
	// Default: "Dockerfile"
	Dockerfile string
}

// Build a container without publishing it.
func (r *Daggerer) BuildOnly(source *Directory, opts ...DaggererBuildOnlyOpts) *Container {
	assertNotNil("source", source)
	q := r.query.Select("buildOnly")
	for i := len(opts) - 1; i >= 0; i-- {
		// `buildEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildEnvFile) {
			q = q.Arg("buildEnvFile", opts[i].BuildEnvFile)
		}
		// `buildValues` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildValues) {
			q = q.Arg("buildValues", opts[i].BuildValues)
		}
		// `buildSecretEnv` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecretEnv) {
			q = q.Arg("buildSecretEnv", opts[i].BuildSecretEnv)
		}
		// `buildSecretIds` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecretIds) {
			q = q.Arg("buildSecretIds", opts[i].BuildSecretIds)
		}
		// `buildSecrets` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecrets) {
			q = q.Arg("buildSecrets", opts[i].BuildSecrets)
		}
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
	}
	q = q.Arg("source", source)

	return &Container{
		query: q,
	}
}

// DaggererDeployOpts contains options for Daggerer.Deploy
type DaggererDeployOpts struct {

	// Default: "latest"
	Tag string
	// SSH key mount path inside the SSH client.
	//
	// Default: "/run/secrets/ssh_key"
	SSHKeyMountPath string
	// Known-hosts mount path inside the SSH client.
	//
	// Default: "/run/secrets/known_hosts"
	KnownHostsMountPath string

	// Default: "compose.yml"
	ComposeFile string
	// Container image used for the SSH client.
	//
	// Default: "alpine:3.24.1"
	SSHImage string
	// Registry password mount path inside the SSH client.
	//
	// Default: "/run/secrets/registry_password"
	RegistryPasswordMountPath string
}

// Deploy an existing image with Compose.
func (r *Daggerer) Deploy(ctx context.Context, registry string, appName string, sshTarget string, sshKey *Secret, knownHosts *Secret, deployDirectory string, deployContainerRuntime string, registryUsername string, registryPassword *Secret, opts ...DaggererDeployOpts) error {
	assertNotNil("sshKey", sshKey)
	assertNotNil("knownHosts", knownHosts)
	assertNotNil("registryPassword", registryPassword)
	if r.deploy != nil {
		return nil
	}
	q := r.query.Select("deploy")
	for i := len(opts) - 1; i >= 0; i-- {
		// `tag` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tag) {
			q = q.Arg("tag", opts[i].Tag)
		}
		// `sshKeyMountPath` optional argument
		if !querybuilder.IsZeroValue(opts[i].SSHKeyMountPath) {
			q = q.Arg("sshKeyMountPath", opts[i].SSHKeyMountPath)
		}
		// `knownHostsMountPath` optional argument
		if !querybuilder.IsZeroValue(opts[i].KnownHostsMountPath) {
			q = q.Arg("knownHostsMountPath", opts[i].KnownHostsMountPath)
		}
		// `composeFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].ComposeFile) {
			q = q.Arg("composeFile", opts[i].ComposeFile)
		}
		// `sshImage` optional argument
		if !querybuilder.IsZeroValue(opts[i].SSHImage) {
			q = q.Arg("sshImage", opts[i].SSHImage)
		}
		// `registryPasswordMountPath` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordMountPath) {
			q = q.Arg("registryPasswordMountPath", opts[i].RegistryPasswordMountPath)
		}
	}
	q = q.Arg("registry", registry)
	q = q.Arg("appName", appName)
	q = q.Arg("sshTarget", sshTarget)
	q = q.Arg("sshKey", sshKey)
	q = q.Arg("knownHosts", knownHosts)
	q = q.Arg("deployDirectory", deployDirectory)
	q = q.Arg("deployContainerRuntime", deployContainerRuntime)
	q = q.Arg("registryUsername", registryUsername)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

// A unique identifier for this Daggerer.
func (r *Daggerer) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Daggerer) XXX_GraphQLType() string {
	return "Daggerer"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Daggerer) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Daggerer) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Daggerer) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Daggerer) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Daggerer{query: selectNode(dag.query, id, "Daggerer")}
	return nil
}

// DaggererReleaseOpts contains options for Daggerer.Release
type DaggererReleaseOpts struct {

	// Default: "latest"
	Tag string
	// SSH key mount path inside the SSH client.
	//
	// Default: "/run/secrets/ssh_key"
	SSHKeyMountPath string
	// Known-hosts mount path inside the SSH client.
	//
	// Default: "/run/secrets/known_hosts"
	KnownHostsMountPath string

	// Default: "compose.yml"
	ComposeFile string
	// Container image used for the SSH client.
	//
	// Default: "alpine:3.24.1"
	SSHImage string
	// Registry password mount path inside helper containers.
	//
	// Default: "/run/secrets/registry_password"
	RegistryPasswordMountPath string
	// Public .env file, parsed by Dagger. Never supply credentials here.
	BuildEnvFile *File
	// Public values constructed with EnvFile.WithVariable; override file values.
	BuildValues *EnvFile
	// Private .env mounted intact as the BuildKit secret build_env.
	BuildSecretEnv *Secret
	// BuildKit secret IDs, paired by position with buildSecrets.
	BuildSecretIds []string
	// Secret values, paired by position with buildSecretIDs.
	BuildSecrets []*Secret

	// Default: "Dockerfile"
	Dockerfile string
}

// Build, publish, and deploy an image tag.
func (r *Daggerer) Release(ctx context.Context, source *Directory, registry string, appName string, sshTarget string, sshKey *Secret, knownHosts *Secret, deployDirectory string, deployContainerRuntime string, registryUsername string, registryPassword *Secret, opts ...DaggererReleaseOpts) error {
	assertNotNil("source", source)
	assertNotNil("sshKey", sshKey)
	assertNotNil("knownHosts", knownHosts)
	assertNotNil("registryPassword", registryPassword)
	if r.release != nil {
		return nil
	}
	q := r.query.Select("release")
	for i := len(opts) - 1; i >= 0; i-- {
		// `tag` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tag) {
			q = q.Arg("tag", opts[i].Tag)
		}
		// `sshKeyMountPath` optional argument
		if !querybuilder.IsZeroValue(opts[i].SSHKeyMountPath) {
			q = q.Arg("sshKeyMountPath", opts[i].SSHKeyMountPath)
		}
		// `knownHostsMountPath` optional argument
		if !querybuilder.IsZeroValue(opts[i].KnownHostsMountPath) {
			q = q.Arg("knownHostsMountPath", opts[i].KnownHostsMountPath)
		}
		// `composeFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].ComposeFile) {
			q = q.Arg("composeFile", opts[i].ComposeFile)
		}
		// `sshImage` optional argument
		if !querybuilder.IsZeroValue(opts[i].SSHImage) {
			q = q.Arg("sshImage", opts[i].SSHImage)
		}
		// `registryPasswordMountPath` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordMountPath) {
			q = q.Arg("registryPasswordMountPath", opts[i].RegistryPasswordMountPath)
		}
		// `buildEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildEnvFile) {
			q = q.Arg("buildEnvFile", opts[i].BuildEnvFile)
		}
		// `buildValues` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildValues) {
			q = q.Arg("buildValues", opts[i].BuildValues)
		}
		// `buildSecretEnv` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecretEnv) {
			q = q.Arg("buildSecretEnv", opts[i].BuildSecretEnv)
		}
		// `buildSecretIds` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecretIds) {
			q = q.Arg("buildSecretIds", opts[i].BuildSecretIds)
		}
		// `buildSecrets` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildSecrets) {
			q = q.Arg("buildSecrets", opts[i].BuildSecrets)
		}
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("registry", registry)
	q = q.Arg("appName", appName)
	q = q.Arg("sshTarget", sshTarget)
	q = q.Arg("sshKey", sshKey)
	q = q.Arg("knownHosts", knownHosts)
	q = q.Arg("deployDirectory", deployDirectory)
	q = q.Arg("deployContainerRuntime", deployContainerRuntime)
	q = q.Arg("registryUsername", registryUsername)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

func (r *Query) Daggerer() *Daggerer { // daggerer (../../../:0:0)
	q := r.query.Select("daggerer")

	return &Daggerer{
		query: q,
	}
}
