// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Daggerer struct { // daggerer (../../../:0:0)
	query *querybuilder.Selection

	build   *string
	deploy  *Void
	id      *ID
	release *Void
}
type WithDaggererFunc func(r *Daggerer) *Daggerer

// With calls the provided function with current Daggerer.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Daggerer) With(f WithDaggererFunc) *Daggerer {
	return f(r)
}

func (r *Daggerer) WithGraphQLQuery(q *querybuilder.Selection) *Daggerer {
	return &Daggerer{
		query: q,
	}
}

// DaggererBuildOpts contains options for Daggerer.Build
type DaggererBuildOpts struct {

	// Default: "latest"
	Tag string
	// Dockerfile path relative to the build context.
	//
	// Default: "Dockerfile"
	Dockerfile string
	// Public .env file, parsed by Dagger. Never supply credentials here.
	BuildEnvFile *File
	// Public dotenv text, parsed by Dagger; overrides buildEnvFile values. Never supply credentials here.
	BuildValues string
}

// Build and publish an image. Returns the deployed image and tag.
func (r *Daggerer) Build(ctx context.Context, source *Directory, registry string, appName string, registryUsername string, registryPassword *Secret, opts ...DaggererBuildOpts) (string, error) {
	assertNotNil("source", source)
	assertNotNil("registryPassword", registryPassword)
	if r.build != nil {
		return *r.build, nil
	}
	q := r.query.Select("build")
	for i := len(opts) - 1; i >= 0; i-- {
		// `tag` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tag) {
			q = q.Arg("tag", opts[i].Tag)
		}
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
		// `buildEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildEnvFile) {
			q = q.Arg("buildEnvFile", opts[i].BuildEnvFile)
		}
		// `buildValues` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildValues) {
			q = q.Arg("buildValues", opts[i].BuildValues)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("registry", registry)
	q = q.Arg("appName", appName)
	q = q.Arg("registryUsername", registryUsername)
	q = q.Arg("registryPassword", registryPassword)

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// DaggererBuildOnlyOpts contains options for Daggerer.BuildOnly
type DaggererBuildOnlyOpts struct {
	// Public .env file, parsed by Dagger. Never supply credentials here.
	BuildEnvFile *File
	// Public dotenv text, parsed by Dagger; overrides buildEnvFile values. Never supply credentials here.
	BuildValues string
	// Dockerfile path relative to the build context.
	//
	// Default: "Dockerfile"
	Dockerfile string
}

// Build a container without publishing it.
func (r *Daggerer) BuildOnly(source *Directory, opts ...DaggererBuildOnlyOpts) *Container {
	assertNotNil("source", source)
	q := r.query.Select("buildOnly")
	for i := len(opts) - 1; i >= 0; i-- {
		// `buildEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildEnvFile) {
			q = q.Arg("buildEnvFile", opts[i].BuildEnvFile)
		}
		// `buildValues` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildValues) {
			q = q.Arg("buildValues", opts[i].BuildValues)
		}
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
	}
	q = q.Arg("source", source)

	return &Container{
		query: q,
	}
}

// DaggererDeployOpts contains options for Daggerer.Deploy
type DaggererDeployOpts struct {

	// Default: "latest"
	Tag string
	// Public dotenv file on the caller, forwarded to the remote Compose process. Never supply credentials here.
	DeployEnvFile *File
	// Public dotenv text; overrides deployEnvFile values. No application variable names are implied.
	DeployValues string
	// Private NAME=literal-value dotenv base file Secret; must use file://.
	DeploySecretEnvFile *Secret

	// Default: "compose.yml"
	ComposeFile string
}

// Deploy an existing image with Compose.
func (r *Daggerer) Deploy(ctx context.Context, registry string, appName string, sshTarget string, sshKey *Secret, knownHosts *Secret, deployDirectory string, deployContainerRuntime string, registryUsername string, registryPassword *Secret, opts ...DaggererDeployOpts) error {
	assertNotNil("sshKey", sshKey)
	assertNotNil("knownHosts", knownHosts)
	assertNotNil("registryPassword", registryPassword)
	if r.deploy != nil {
		return nil
	}
	q := r.query.Select("deploy")
	for i := len(opts) - 1; i >= 0; i-- {
		// `tag` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tag) {
			q = q.Arg("tag", opts[i].Tag)
		}
		// `deployEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].DeployEnvFile) {
			q = q.Arg("deployEnvFile", opts[i].DeployEnvFile)
		}
		// `deployValues` optional argument
		if !querybuilder.IsZeroValue(opts[i].DeployValues) {
			q = q.Arg("deployValues", opts[i].DeployValues)
		}
		// `deploySecretEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].DeploySecretEnvFile) {
			q = q.Arg("deploySecretEnvFile", opts[i].DeploySecretEnvFile)
		}
		// `composeFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].ComposeFile) {
			q = q.Arg("composeFile", opts[i].ComposeFile)
		}
	}
	q = q.Arg("registry", registry)
	q = q.Arg("appName", appName)
	q = q.Arg("sshTarget", sshTarget)
	q = q.Arg("sshKey", sshKey)
	q = q.Arg("knownHosts", knownHosts)
	q = q.Arg("deployDirectory", deployDirectory)
	q = q.Arg("deployContainerRuntime", deployContainerRuntime)
	q = q.Arg("registryUsername", registryUsername)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

// A unique identifier for this Daggerer.
func (r *Daggerer) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Daggerer) XXX_GraphQLType() string {
	return "Daggerer"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Daggerer) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Daggerer) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Daggerer) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Daggerer) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Daggerer{query: selectNode(dag.query, id, "Daggerer")}
	return nil
}

// DaggererReleaseOpts contains options for Daggerer.Release
type DaggererReleaseOpts struct {
	// What tag to use for this release
	//
	// Default: "latest"
	Tag string
	// Public dotenv file on the caller, forwarded to the remote Compose process. Never supply credentials here.
	DeployEnvFile *File
	// Public dotenv text; overrides deployEnvFile values. No application variable names are implied.
	DeployValues string
	// Private NAME=literal-value dotenv base file Secret; must use file://.
	DeploySecretEnvFile *Secret
	// Compose file name that is in the deploy directory.
	//
	// Default: "compose.yml"
	ComposeFile string
	// Public .env file, parsed by Dagger. You really shouldn't supply credentials here.
	BuildEnvFile *File
	// Public dotenv text, parsed by Dagger; overrides buildEnvFile values. Never supply credentials here.
	BuildValues string

	// Default: "Dockerfile"
	Dockerfile string
}

// Build, publish, and deploy an image tag.
func (r *Daggerer) Release(ctx context.Context, source *Directory, registry string, appName string, sshTarget string, sshKey *Secret, knownHosts *Secret, deployDirectory string, deployContainerRuntime string, registryUsername string, registryPassword *Secret, opts ...DaggererReleaseOpts) error {
	assertNotNil("source", source)
	assertNotNil("sshKey", sshKey)
	assertNotNil("knownHosts", knownHosts)
	assertNotNil("registryPassword", registryPassword)
	if r.release != nil {
		return nil
	}
	q := r.query.Select("release")
	for i := len(opts) - 1; i >= 0; i-- {
		// `tag` optional argument
		if !querybuilder.IsZeroValue(opts[i].Tag) {
			q = q.Arg("tag", opts[i].Tag)
		}
		// `deployEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].DeployEnvFile) {
			q = q.Arg("deployEnvFile", opts[i].DeployEnvFile)
		}
		// `deployValues` optional argument
		if !querybuilder.IsZeroValue(opts[i].DeployValues) {
			q = q.Arg("deployValues", opts[i].DeployValues)
		}
		// `deploySecretEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].DeploySecretEnvFile) {
			q = q.Arg("deploySecretEnvFile", opts[i].DeploySecretEnvFile)
		}
		// `composeFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].ComposeFile) {
			q = q.Arg("composeFile", opts[i].ComposeFile)
		}
		// `buildEnvFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildEnvFile) {
			q = q.Arg("buildEnvFile", opts[i].BuildEnvFile)
		}
		// `buildValues` optional argument
		if !querybuilder.IsZeroValue(opts[i].BuildValues) {
			q = q.Arg("buildValues", opts[i].BuildValues)
		}
		// `dockerfile` optional argument
		if !querybuilder.IsZeroValue(opts[i].Dockerfile) {
			q = q.Arg("dockerfile", opts[i].Dockerfile)
		}
	}
	q = q.Arg("source", source)
	q = q.Arg("registry", registry)
	q = q.Arg("appName", appName)
	q = q.Arg("sshTarget", sshTarget)
	q = q.Arg("sshKey", sshKey)
	q = q.Arg("knownHosts", knownHosts)
	q = q.Arg("deployDirectory", deployDirectory)
	q = q.Arg("deployContainerRuntime", deployContainerRuntime)
	q = q.Arg("registryUsername", registryUsername)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

// WithBuildSecret adds a named BuildKit secret to the next chained build, build-only, or release call.
func (r *Daggerer) WithBuildSecret(id string, secret *Secret) *Daggerer {
	assertNotNil("secret", secret)
	q := r.query.Select("withBuildSecret")
	q = q.Arg("id", id)
	q = q.Arg("secret", secret)

	return &Daggerer{
		query: q,
	}
}

func (r *Query) Daggerer() *Daggerer { // daggerer (../../../:0:0)
	q := r.query.Select("daggerer")

	return &Daggerer{
		query: q,
	}
}
