// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/daggerer/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Daggerer) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Daggerer) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Daggerer":
		switch fnName {
		case "Build":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var appName string
			if inputArgs["appName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["appName"]), &appName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg appName", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var registryUsername string
			if inputArgs["registryUsername"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryUsername"]), &registryUsername)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryUsername", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			var registryPasswordMountPath string
			if inputArgs["registryPasswordMountPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPasswordMountPath"]), &registryPasswordMountPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPasswordMountPath", err))
				}
			}
			var buildEnvFile *dagger.File
			if inputArgs["buildEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildEnvFile"]), &buildEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildEnvFile", err))
				}
			}
			var buildValues *dagger.EnvFile
			if inputArgs["buildValues"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildValues"]), &buildValues)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildValues", err))
				}
			}
			var buildSecretEnv *dagger.Secret
			if inputArgs["buildSecretEnv"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecretEnv"]), &buildSecretEnv)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecretEnv", err))
				}
			}
			var buildSecretIds []string
			if inputArgs["buildSecretIDs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecretIDs"]), &buildSecretIds)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecretIDs", err))
				}
			}
			var buildSecrets []*dagger.Secret
			if inputArgs["buildSecrets"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecrets"]), &buildSecrets)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecrets", err))
				}
			}
			var dockerfile string
			if inputArgs["dockerfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dockerfile"]), &dockerfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dockerfile", err))
				}
			}
			return (*Daggerer).Build(&parent, ctx, source, registry, appName, tag, registryUsername, registryPassword, registryPasswordMountPath, buildEnvFile, buildValues, buildSecretEnv, buildSecretIds, buildSecrets, dockerfile)
		case "BuildOnly":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var buildEnvFile *dagger.File
			if inputArgs["buildEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildEnvFile"]), &buildEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildEnvFile", err))
				}
			}
			var buildValues *dagger.EnvFile
			if inputArgs["buildValues"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildValues"]), &buildValues)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildValues", err))
				}
			}
			var buildSecretEnv *dagger.Secret
			if inputArgs["buildSecretEnv"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecretEnv"]), &buildSecretEnv)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecretEnv", err))
				}
			}
			var buildSecretIds []string
			if inputArgs["buildSecretIDs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecretIDs"]), &buildSecretIds)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecretIDs", err))
				}
			}
			var buildSecrets []*dagger.Secret
			if inputArgs["buildSecrets"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecrets"]), &buildSecrets)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecrets", err))
				}
			}
			var dockerfile string
			if inputArgs["dockerfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dockerfile"]), &dockerfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dockerfile", err))
				}
			}
			return (*Daggerer).BuildOnly(&parent, ctx, source, buildEnvFile, buildValues, buildSecretEnv, buildSecretIds, buildSecrets, dockerfile)
		case "Deploy":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var appName string
			if inputArgs["appName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["appName"]), &appName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg appName", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var sshTarget string
			if inputArgs["sshTarget"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshTarget"]), &sshTarget)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshTarget", err))
				}
			}
			var sshKey *dagger.Secret
			if inputArgs["sshKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshKey"]), &sshKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshKey", err))
				}
			}
			var knownHosts *dagger.Secret
			if inputArgs["knownHosts"] != nil {
				err = json.Unmarshal([]byte(inputArgs["knownHosts"]), &knownHosts)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg knownHosts", err))
				}
			}
			var sshKeyMountPath string
			if inputArgs["sshKeyMountPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshKeyMountPath"]), &sshKeyMountPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshKeyMountPath", err))
				}
			}
			var knownHostsMountPath string
			if inputArgs["knownHostsMountPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["knownHostsMountPath"]), &knownHostsMountPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg knownHostsMountPath", err))
				}
			}
			var deployDirectory string
			if inputArgs["deployDirectory"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployDirectory"]), &deployDirectory)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployDirectory", err))
				}
			}
			var deployContainerRuntime string
			if inputArgs["deployContainerRuntime"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployContainerRuntime"]), &deployContainerRuntime)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployContainerRuntime", err))
				}
			}
			var composeFile string
			if inputArgs["composeFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["composeFile"]), &composeFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg composeFile", err))
				}
			}
			var sshImage string
			if inputArgs["sshImage"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshImage"]), &sshImage)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshImage", err))
				}
			}
			var registryUsername string
			if inputArgs["registryUsername"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryUsername"]), &registryUsername)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryUsername", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			var registryPasswordMountPath string
			if inputArgs["registryPasswordMountPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPasswordMountPath"]), &registryPasswordMountPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPasswordMountPath", err))
				}
			}
			return nil, (*Daggerer).Deploy(&parent, ctx, registry, appName, tag, sshTarget, sshKey, knownHosts, sshKeyMountPath, knownHostsMountPath, deployDirectory, deployContainerRuntime, composeFile, sshImage, registryUsername, registryPassword, registryPasswordMountPath)
		case "Release":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var appName string
			if inputArgs["appName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["appName"]), &appName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg appName", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var sshTarget string
			if inputArgs["sshTarget"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshTarget"]), &sshTarget)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshTarget", err))
				}
			}
			var sshKey *dagger.Secret
			if inputArgs["sshKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshKey"]), &sshKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshKey", err))
				}
			}
			var knownHosts *dagger.Secret
			if inputArgs["knownHosts"] != nil {
				err = json.Unmarshal([]byte(inputArgs["knownHosts"]), &knownHosts)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg knownHosts", err))
				}
			}
			var sshKeyMountPath string
			if inputArgs["sshKeyMountPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshKeyMountPath"]), &sshKeyMountPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshKeyMountPath", err))
				}
			}
			var knownHostsMountPath string
			if inputArgs["knownHostsMountPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["knownHostsMountPath"]), &knownHostsMountPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg knownHostsMountPath", err))
				}
			}
			var deployDirectory string
			if inputArgs["deployDirectory"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployDirectory"]), &deployDirectory)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployDirectory", err))
				}
			}
			var deployContainerRuntime string
			if inputArgs["deployContainerRuntime"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployContainerRuntime"]), &deployContainerRuntime)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployContainerRuntime", err))
				}
			}
			var composeFile string
			if inputArgs["composeFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["composeFile"]), &composeFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg composeFile", err))
				}
			}
			var sshImage string
			if inputArgs["sshImage"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshImage"]), &sshImage)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshImage", err))
				}
			}
			var registryUsername string
			if inputArgs["registryUsername"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryUsername"]), &registryUsername)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryUsername", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			var registryPasswordMountPath string
			if inputArgs["registryPasswordMountPath"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPasswordMountPath"]), &registryPasswordMountPath)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPasswordMountPath", err))
				}
			}
			var buildEnvFile *dagger.File
			if inputArgs["buildEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildEnvFile"]), &buildEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildEnvFile", err))
				}
			}
			var buildValues *dagger.EnvFile
			if inputArgs["buildValues"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildValues"]), &buildValues)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildValues", err))
				}
			}
			var buildSecretEnv *dagger.Secret
			if inputArgs["buildSecretEnv"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecretEnv"]), &buildSecretEnv)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecretEnv", err))
				}
			}
			var buildSecretIds []string
			if inputArgs["buildSecretIDs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecretIDs"]), &buildSecretIds)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecretIDs", err))
				}
			}
			var buildSecrets []*dagger.Secret
			if inputArgs["buildSecrets"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildSecrets"]), &buildSecrets)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildSecrets", err))
				}
			}
			var dockerfile string
			if inputArgs["dockerfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dockerfile"]), &dockerfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dockerfile", err))
				}
			}
			return nil, (*Daggerer).Release(&parent, ctx, source, registry, appName, tag, sshTarget, sshKey, knownHosts, sshKeyMountPath, knownHostsMountPath, deployDirectory, deployContainerRuntime, composeFile, sshImage, registryUsername, registryPassword, registryPasswordMountPath, buildEnvFile, buildValues, buildSecretEnv, buildSecretIds, buildSecrets, dockerfile)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Daggerer", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 13, 6)}).
					WithFunction(
						dag.Function("Build",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Build and publish an image.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 78, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Application checkout to use as the build context.", SourceMap: dag.SourceMap("main.go", 81, 2)}).
							WithArg("registry", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry hostname, optionally including its port.", SourceMap: dag.SourceMap("main.go", 83, 2)}).
							WithArg("appName", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Image repository name inside the registry.", SourceMap: dag.SourceMap("main.go", 85, 2)}).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 87, 2), DefaultValue: dagger.JSON("\"latest\"")}).
							WithArg("registryUsername", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 88, 2)}).
							WithArg("registryPassword", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 89, 2)}).
							WithArg("registryPasswordMountPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry password mount path inside the registry client.", SourceMap: dag.SourceMap("main.go", 92, 2), DefaultValue: dagger.JSON("\"/run/secrets/registry_password\"")}).
							WithArg("buildEnvFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public .env file, parsed by Dagger. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 95, 2)}).
							WithArg("buildValues", dag.TypeDef().WithObject("EnvFile").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public values constructed with EnvFile.WithVariable; override file values.", SourceMap: dag.SourceMap("main.go", 98, 2)}).
							WithArg("buildSecretEnv", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Private .env mounted intact as the BuildKit secret build_env.", SourceMap: dag.SourceMap("main.go", 101, 2)}).
							WithArg("buildSecretIDs", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{Description: "BuildKit secret IDs, paired by position with buildSecrets.", SourceMap: dag.SourceMap("main.go", 104, 2)}).
							WithArg("buildSecrets", dag.TypeDef().WithListOf(dag.TypeDef().WithObject("Secret")).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Secret values, paired by position with buildSecretIDs.", SourceMap: dag.SourceMap("main.go", 107, 2)}).
							WithArg("dockerfile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Dockerfile path relative to the build context.", SourceMap: dag.SourceMap("main.go", 110, 2), DefaultValue: dagger.JSON("\"Dockerfile\"")})).
					WithFunction(
						dag.Function("BuildOnly",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Build a container without publishing it.").
							WithSourceMap(dag.SourceMap("main.go", 16, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Application checkout to use as the build context.", SourceMap: dag.SourceMap("main.go", 19, 2)}).
							WithArg("buildEnvFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public .env file, parsed by Dagger. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 22, 2)}).
							WithArg("buildValues", dag.TypeDef().WithObject("EnvFile").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public values constructed with EnvFile.WithVariable; override file values.", SourceMap: dag.SourceMap("main.go", 25, 2)}).
							WithArg("buildSecretEnv", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Private .env mounted intact as the BuildKit secret build_env.", SourceMap: dag.SourceMap("main.go", 28, 2)}).
							WithArg("buildSecretIDs", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{Description: "BuildKit secret IDs, paired by position with buildSecrets.", SourceMap: dag.SourceMap("main.go", 31, 2)}).
							WithArg("buildSecrets", dag.TypeDef().WithListOf(dag.TypeDef().WithObject("Secret")).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Secret values, paired by position with buildSecretIDs.", SourceMap: dag.SourceMap("main.go", 34, 2)}).
							WithArg("dockerfile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Dockerfile path relative to the build context.", SourceMap: dag.SourceMap("main.go", 37, 2), DefaultValue: dagger.JSON("\"Dockerfile\"")})).
					WithFunction(
						dag.Function("Deploy",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Deploy an existing image with Compose.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 194, 1)).
							WithArg("registry", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry hostname, optionally including its port.", SourceMap: dag.SourceMap("main.go", 197, 2)}).
							WithArg("appName", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Image repository name inside the registry.", SourceMap: dag.SourceMap("main.go", 199, 2)}).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 201, 2), DefaultValue: dagger.JSON("\"latest\"")}).
							WithArg("sshTarget", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "SSH destination in user@host form.", SourceMap: dag.SourceMap("main.go", 203, 2)}).
							WithArg("sshKey", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 204, 2)}).
							WithArg("knownHosts", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 205, 2)}).
							WithArg("sshKeyMountPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "SSH key mount path inside the SSH client.", SourceMap: dag.SourceMap("main.go", 208, 2), DefaultValue: dagger.JSON("\"/run/secrets/ssh_key\"")}).
							WithArg("knownHostsMountPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Known-hosts mount path inside the SSH client.", SourceMap: dag.SourceMap("main.go", 211, 2), DefaultValue: dagger.JSON("\"/run/secrets/known_hosts\"")}).
							WithArg("deployDirectory", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Remote directory relative to the SSH user's home.", SourceMap: dag.SourceMap("main.go", 213, 2)}).
							WithArg("deployContainerRuntime", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Required deployment CLI: docker or podman. Supplied by the workflow preset.", SourceMap: dag.SourceMap("main.go", 215, 2)}).
							WithArg("composeFile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 217, 2), DefaultValue: dagger.JSON("\"compose.yml\"")}).
							WithArg("sshImage", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Container image used for the SSH client.", SourceMap: dag.SourceMap("main.go", 220, 2), DefaultValue: dagger.JSON("\"alpine:3.24.1\"")}).
							WithArg("registryUsername", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 221, 2)}).
							WithArg("registryPassword", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 222, 2)}).
							WithArg("registryPasswordMountPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry password mount path inside the SSH client.", SourceMap: dag.SourceMap("main.go", 225, 2), DefaultValue: dagger.JSON("\"/run/secrets/registry_password\"")})).
					WithFunction(
						dag.Function("Release",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Build, publish, and deploy an image tag.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 131, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 133, 2)}).
							WithArg("registry", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry hostname, optionally including its port.", SourceMap: dag.SourceMap("main.go", 135, 2)}).
							WithArg("appName", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Image repository name inside the registry.", SourceMap: dag.SourceMap("main.go", 137, 2)}).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 139, 2), DefaultValue: dagger.JSON("\"latest\"")}).
							WithArg("sshTarget", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "SSH destination in user@host form.", SourceMap: dag.SourceMap("main.go", 141, 2)}).
							WithArg("sshKey", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 142, 2)}).
							WithArg("knownHosts", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 143, 2)}).
							WithArg("sshKeyMountPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "SSH key mount path inside the SSH client.", SourceMap: dag.SourceMap("main.go", 146, 2), DefaultValue: dagger.JSON("\"/run/secrets/ssh_key\"")}).
							WithArg("knownHostsMountPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Known-hosts mount path inside the SSH client.", SourceMap: dag.SourceMap("main.go", 149, 2), DefaultValue: dagger.JSON("\"/run/secrets/known_hosts\"")}).
							WithArg("deployDirectory", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Remote directory relative to the SSH user's home.", SourceMap: dag.SourceMap("main.go", 151, 2)}).
							WithArg("deployContainerRuntime", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Required deployment CLI: docker or podman. Supplied by the workflow preset.", SourceMap: dag.SourceMap("main.go", 153, 2)}).
							WithArg("composeFile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 155, 2), DefaultValue: dagger.JSON("\"compose.yml\"")}).
							WithArg("sshImage", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Container image used for the SSH client.", SourceMap: dag.SourceMap("main.go", 158, 2), DefaultValue: dagger.JSON("\"alpine:3.24.1\"")}).
							WithArg("registryUsername", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 159, 2)}).
							WithArg("registryPassword", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 160, 2)}).
							WithArg("registryPasswordMountPath", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry password mount path inside helper containers.", SourceMap: dag.SourceMap("main.go", 163, 2), DefaultValue: dagger.JSON("\"/run/secrets/registry_password\"")}).
							WithArg("buildEnvFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public .env file, parsed by Dagger. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 166, 2)}).
							WithArg("buildValues", dag.TypeDef().WithObject("EnvFile").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public values constructed with EnvFile.WithVariable; override file values.", SourceMap: dag.SourceMap("main.go", 169, 2)}).
							WithArg("buildSecretEnv", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Private .env mounted intact as the BuildKit secret build_env.", SourceMap: dag.SourceMap("main.go", 172, 2)}).
							WithArg("buildSecretIDs", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{Description: "BuildKit secret IDs, paired by position with buildSecrets.", SourceMap: dag.SourceMap("main.go", 175, 2)}).
							WithArg("buildSecrets", dag.TypeDef().WithListOf(dag.TypeDef().WithObject("Secret")).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Secret values, paired by position with buildSecretIDs.", SourceMap: dag.SourceMap("main.go", 178, 2)}).
							WithArg("dockerfile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 180, 2), DefaultValue: dagger.JSON("\"Dockerfile\"")}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
