// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/daggerer/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Daggerer) MarshalJSON() ([]byte, error) {
	var concrete struct {
		BuildSecretIDs    []string
		BuildSecretValues []*dagger.Secret
	}
	concrete.BuildSecretIDs = r.BuildSecretIDs
	concrete.BuildSecretValues = r.BuildSecretValues
	return json.Marshal(&concrete)
}

func (r *Daggerer) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		BuildSecretIDs    []string
		BuildSecretValues []*dagger.Secret
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.BuildSecretIDs = concrete.BuildSecretIDs
	r.BuildSecretValues = concrete.BuildSecretValues
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Daggerer":
		switch fnName {
		case "Build":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var appName string
			if inputArgs["appName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["appName"]), &appName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg appName", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var registryUsername string
			if inputArgs["registryUsername"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryUsername"]), &registryUsername)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryUsername", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			var dockerfile string
			if inputArgs["dockerfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dockerfile"]), &dockerfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dockerfile", err))
				}
			}
			var buildEnvFile *dagger.File
			if inputArgs["buildEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildEnvFile"]), &buildEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildEnvFile", err))
				}
			}
			var buildValues string
			if inputArgs["buildValues"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildValues"]), &buildValues)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildValues", err))
				}
			}
			return (*Daggerer).Build(&parent, ctx, source, registry, appName, tag, registryUsername, registryPassword, dockerfile, buildEnvFile, buildValues)
		case "BuildDockerfile":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var buildEnvFile *dagger.File
			if inputArgs["buildEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildEnvFile"]), &buildEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildEnvFile", err))
				}
			}
			var buildValues string
			if inputArgs["buildValues"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildValues"]), &buildValues)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildValues", err))
				}
			}
			var dockerfile string
			if inputArgs["dockerfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dockerfile"]), &dockerfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dockerfile", err))
				}
			}
			return (*Daggerer).BuildDockerfile(&parent, ctx, source, buildEnvFile, buildValues, dockerfile)
		case "Deploy":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var appName string
			if inputArgs["appName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["appName"]), &appName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg appName", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var sshTarget string
			if inputArgs["sshTarget"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshTarget"]), &sshTarget)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshTarget", err))
				}
			}
			var sshKey *dagger.Secret
			if inputArgs["sshKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshKey"]), &sshKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshKey", err))
				}
			}
			var knownHosts *dagger.Secret
			if inputArgs["knownHosts"] != nil {
				err = json.Unmarshal([]byte(inputArgs["knownHosts"]), &knownHosts)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg knownHosts", err))
				}
			}
			var deployDirectory string
			if inputArgs["deployDirectory"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployDirectory"]), &deployDirectory)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployDirectory", err))
				}
			}
			var deployEnvFile *dagger.File
			if inputArgs["deployEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployEnvFile"]), &deployEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployEnvFile", err))
				}
			}
			var deployValues string
			if inputArgs["deployValues"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployValues"]), &deployValues)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployValues", err))
				}
			}
			var deploySecretEnvFile *dagger.Secret
			if inputArgs["deploySecretEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deploySecretEnvFile"]), &deploySecretEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deploySecretEnvFile", err))
				}
			}
			var deployContainerRuntime string
			if inputArgs["deployContainerRuntime"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployContainerRuntime"]), &deployContainerRuntime)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployContainerRuntime", err))
				}
			}
			var composeFile string
			if inputArgs["composeFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["composeFile"]), &composeFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg composeFile", err))
				}
			}
			var registryUsername string
			if inputArgs["registryUsername"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryUsername"]), &registryUsername)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryUsername", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			return nil, (*Daggerer).Deploy(&parent, ctx, registry, appName, tag, sshTarget, sshKey, knownHosts, deployDirectory, deployEnvFile, deployValues, deploySecretEnvFile, deployContainerRuntime, composeFile, registryUsername, registryPassword)
		case "Release":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var appName string
			if inputArgs["appName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["appName"]), &appName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg appName", err))
				}
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var sshTarget string
			if inputArgs["sshTarget"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshTarget"]), &sshTarget)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshTarget", err))
				}
			}
			var sshKey *dagger.Secret
			if inputArgs["sshKey"] != nil {
				err = json.Unmarshal([]byte(inputArgs["sshKey"]), &sshKey)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg sshKey", err))
				}
			}
			var knownHosts *dagger.Secret
			if inputArgs["knownHosts"] != nil {
				err = json.Unmarshal([]byte(inputArgs["knownHosts"]), &knownHosts)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg knownHosts", err))
				}
			}
			var deployDirectory string
			if inputArgs["deployDirectory"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployDirectory"]), &deployDirectory)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployDirectory", err))
				}
			}
			var deployEnvFile *dagger.File
			if inputArgs["deployEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployEnvFile"]), &deployEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployEnvFile", err))
				}
			}
			var deployValues string
			if inputArgs["deployValues"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployValues"]), &deployValues)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployValues", err))
				}
			}
			var deploySecretEnvFile *dagger.Secret
			if inputArgs["deploySecretEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deploySecretEnvFile"]), &deploySecretEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deploySecretEnvFile", err))
				}
			}
			var composeFile string
			if inputArgs["composeFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["composeFile"]), &composeFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg composeFile", err))
				}
			}
			var deployContainerRuntime string
			if inputArgs["deployContainerRuntime"] != nil {
				err = json.Unmarshal([]byte(inputArgs["deployContainerRuntime"]), &deployContainerRuntime)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg deployContainerRuntime", err))
				}
			}
			var registryUsername string
			if inputArgs["registryUsername"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryUsername"]), &registryUsername)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryUsername", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			var buildEnvFile *dagger.File
			if inputArgs["buildEnvFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildEnvFile"]), &buildEnvFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildEnvFile", err))
				}
			}
			var buildValues string
			if inputArgs["buildValues"] != nil {
				err = json.Unmarshal([]byte(inputArgs["buildValues"]), &buildValues)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg buildValues", err))
				}
			}
			var dockerfile string
			if inputArgs["dockerfile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dockerfile"]), &dockerfile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dockerfile", err))
				}
			}
			return nil, (*Daggerer).Release(&parent, ctx, source, registry, appName, tag, sshTarget, sshKey, knownHosts, deployDirectory, deployEnvFile, deployValues, deploySecretEnvFile, composeFile, deployContainerRuntime, registryUsername, registryPassword, buildEnvFile, buildValues, dockerfile)
		case "WithBuildSecret":
			var parent Daggerer
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var id string
			if inputArgs["id"] != nil {
				err = json.Unmarshal([]byte(inputArgs["id"]), &id)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg id", err))
				}
			}
			var secret *dagger.Secret
			if inputArgs["secret"] != nil {
				err = json.Unmarshal([]byte(inputArgs["secret"]), &secret)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg secret", err))
				}
			}
			return (*Daggerer).WithBuildSecret(&parent, ctx, id, secret)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Daggerer", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 12, 6)}).
					WithFunction(
						dag.Function("Build",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Build and publish an image. Returns the deployed image and tag.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 58, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Application checkout to use as the build context.", SourceMap: dag.SourceMap("main.go", 61, 2)}).
							WithArg("registry", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry hostname, optionally including its port.", SourceMap: dag.SourceMap("main.go", 63, 2)}).
							WithArg("appName", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Image repository name inside the registry.", SourceMap: dag.SourceMap("main.go", 65, 2)}).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 67, 2), DefaultValue: dagger.JSON("\"latest\"")}).
							WithArg("registryUsername", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 68, 2)}).
							WithArg("registryPassword", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 69, 2)}).
							WithArg("dockerfile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Dockerfile path relative to the build context.", SourceMap: dag.SourceMap("main.go", 72, 2), DefaultValue: dagger.JSON("\"Dockerfile\"")}).
							WithArg("buildEnvFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public .env file, parsed by Dagger. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 75, 2)}).
							WithArg("buildValues", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public dotenv text, parsed by Dagger; overrides buildEnvFile values. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 78, 2)})).
					WithFunction(
						dag.Function("BuildDockerfile",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Build a container image from a Dockerfile without publishing it.").
							WithSourceMap(dag.SourceMap("main.go", 26, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "Application checkout to use as the build context.", SourceMap: dag.SourceMap("main.go", 29, 2)}).
							WithArg("buildEnvFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public .env file, parsed by Dagger. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 32, 2)}).
							WithArg("buildValues", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public dotenv text, parsed by Dagger; overrides buildEnvFile values. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 35, 2)}).
							WithArg("dockerfile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Dockerfile path relative to the build context.", SourceMap: dag.SourceMap("main.go", 38, 2), DefaultValue: dagger.JSON("\"Dockerfile\"")})).
					WithFunction(
						dag.Function("Deploy",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Deploy an existing image with Compose.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 162, 1)).
							WithArg("registry", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry hostname, optionally including its port.", SourceMap: dag.SourceMap("main.go", 165, 2)}).
							WithArg("appName", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Image repository name inside the registry.", SourceMap: dag.SourceMap("main.go", 167, 2)}).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 169, 2), DefaultValue: dagger.JSON("\"latest\"")}).
							WithArg("sshTarget", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "ssh destination: user@host", SourceMap: dag.SourceMap("main.go", 171, 2)}).
							WithArg("sshKey", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 172, 2)}).
							WithArg("knownHosts", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 173, 2)}).
							WithArg("deployDirectory", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Remote directory relative to the SSH user's home.", SourceMap: dag.SourceMap("main.go", 175, 2)}).
							WithArg("deployEnvFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public dotenv file on the caller, forwarded to the remote Compose process. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 178, 2)}).
							WithArg("deployValues", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public dotenv text; overrides deployEnvFile values. No application variable names are implied.", SourceMap: dag.SourceMap("main.go", 181, 2)}).
							WithArg("deploySecretEnvFile", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Private NAME=literal-value dotenv base file Secret; must use file://.", SourceMap: dag.SourceMap("main.go", 184, 2)}).
							WithArg("deployContainerRuntime", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Required deployment CLI: docker or podman. Supplied by the workflow preset.", SourceMap: dag.SourceMap("main.go", 186, 2)}).
							WithArg("composeFile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 188, 2), DefaultValue: dagger.JSON("\"compose.yml\"")}).
							WithArg("registryUsername", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 189, 2)}).
							WithArg("registryPassword", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 190, 2)})).
					WithFunction(
						dag.Function("Release",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Build, publish, and deploy an image tag.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 99, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 101, 2)}).
							WithArg("registry", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "OCI image registry host name.", SourceMap: dag.SourceMap("main.go", 103, 2)}).
							WithArg("appName", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "OCI image repository name inside the registry.", SourceMap: dag.SourceMap("main.go", 105, 2)}).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "What tag to use for this release", SourceMap: dag.SourceMap("main.go", 108, 2), DefaultValue: dagger.JSON("\"latest\"")}).
							WithArg("sshTarget", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "ssh deploy destination target in user@host form", SourceMap: dag.SourceMap("main.go", 110, 2)}).
							WithArg("sshKey", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 111, 2)}).
							WithArg("knownHosts", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 112, 2)}).
							WithArg("deployDirectory", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Remote directory relative to the SSH user's home", SourceMap: dag.SourceMap("main.go", 114, 2)}).
							WithArg("deployEnvFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public dotenv file on the caller, forwarded to the remote Compose process. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 117, 2)}).
							WithArg("deployValues", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public dotenv text; overrides deployEnvFile values. No application variable names are implied.", SourceMap: dag.SourceMap("main.go", 120, 2)}).
							WithArg("deploySecretEnvFile", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Private NAME=literal-value dotenv base file Secret; must use file://.", SourceMap: dag.SourceMap("main.go", 123, 2)}).
							WithArg("composeFile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Compose file name that is in the deploy directory.", SourceMap: dag.SourceMap("main.go", 126, 2), DefaultValue: dagger.JSON("\"compose.yml\"")}).
							WithArg("deployContainerRuntime", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Required deployment CLI: docker or podman.", SourceMap: dag.SourceMap("main.go", 128, 2)}).
							WithArg("registryUsername", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 129, 2)}).
							WithArg("registryPassword", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 130, 2)}).
							WithArg("buildEnvFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public .env file, parsed by Dagger. You really shouldn't supply credentials here.", SourceMap: dag.SourceMap("main.go", 133, 2)}).
							WithArg("buildValues", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Public dotenv text, parsed by Dagger; overrides buildEnvFile values. Never supply credentials here.", SourceMap: dag.SourceMap("main.go", 136, 2)}).
							WithArg("dockerfile", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 138, 2), DefaultValue: dagger.JSON("\"Dockerfile\"")})).
					WithFunction(
						dag.Function("WithBuildSecret",
							dag.TypeDef().WithObject("Daggerer")).
							WithDescription("WithBuildSecret adds a named BuildKit secret to the next chained build, build-dockerfile, or release call.").
							WithSourceMap(dag.SourceMap("secrets.go", 21, 1)).
							WithArg("id", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Dockerfile secret ID used by RUN --mount=type=secret,id=<id>.", SourceMap: dag.SourceMap("secrets.go", 24, 2)}).
							WithArg("secret", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{Description: "Caller-local secret file. Must use file://.", SourceMap: dag.SourceMap("secrets.go", 26, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
